In [18]:
using LinearAlgebra

In [1]:
using Pkg
Pkg.add("DataFrames")
Pkg.add("CSV")

    Updating registry at `~/.julia/registries/General.toml`


   Resolving package versions...


  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [1]:
struct LinearRegression
    add_const::Bool
end

function LinearRegression()
    return LinearRegression(false)
end

LinearRegression

In [62]:
struct RidgeRegression
    lambda::Float64
end

function RidgeRegression()
    return RidgeRegression(0.)
end


RidgeRegression

In [3]:
function fit(X::Matrix, y::Array, model::RidgeRegression)
    xt = transpose(X)
    xtx = xt*X
    xty = xt*y
    inv(xtx+model.lambda*I)*xty
end

fit (generic function with 1 method)

In [36]:
model = RidgeRegression(0.5)
fit(x, y, model)

2-element Vector{Float64}:
  1.3866666666666676
 14.453333333333342

In [53]:
cat(x, ones(size(x)[1]), dims=2)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  2.0  1.0
 2.0  4.0  1.0

In [3]:
Base.@kwdef struct RidgeRegression
    lambda::Float64 = 0.
    add_const::Bool = false
end

# function RidgeRegression()
#     return RidgeRegression(0., false)
# end

RidgeRegression

In [6]:
rr = RidgeRegression()

RidgeRegression(0.0, false)

In [60]:
function fit(X, y, model)
    error("error! $model is not supported type")
end

function fit(X::Matrix, y::Array, model::LinearRegression)
    if model.add_const
        X = cat(X, ones(size(X)[1]), dims=2)
    end
    xt = transpose(X)
    xtx = xt*X
    xty = xt*y
    inv(xtx)*xty
end

fit (generic function with 3 methods)

In [61]:
lr = LinearRegression(true)
fit(x,y,lr)

ErrorException: type LinearRegression has no field add_const

In [6]:
using CSV
using DataFrames

sample_data = CSV.read("/workdir/sample_data/sample.csv", DataFrame)

3×3 DataFrame
 Row │ A      B      C     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1     10
   2 │     1      2     32
   3 │     2      4     63

In [7]:
a = Matrix(sample_data)
x = a[:,begin:2]
y = a[:,end]
y

3-element Vector{Int64}:
 10
 32
 63

In [9]:
model = LinearRegression()
beta = fit(x, y, model)

2-element Vector{Float64}:
 -11.600000000000161
  21.600000000000097